version: 2
jobs:
  prepare_ci:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  AssembleDemo:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: ./gradlew assembleDemo
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports

  AssembleProduction:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: ./gradlew assembleProduction
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: ./gradlew test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
  lint:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: ./gradlew lint
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
workflows:
  version: 2
  main:
    jobs:
      - prepare_ci
      - AssembleDemoDebug:
          requires:
            - prepare_ci
      - AssembleDemoRelease:
          requires:
            - prepare_ci
      - AssembleProductionDebug:
          requires:
            - prepare_ci
      - AssembleProductionRelease:
          requires:
            - prepare_ci
      - test:
          requires:
            - AssembleDemoDebug
      - lint:
          requires:
            - AssembleDemoDebug